spring:
  application:
    name: catalog-service
  datasource:
    url: ${PASSLY_CATALOG_DB_URL:jdbc:postgresql://localhost:5432/catalog}
    username: ${PASSLY_CATALOG_DB_USER:passly}
    password: ${PASSLY_CATALOG_DB_PASSWORD:passly}
  data:
    web:
      pageable:
        max-page-size: 100
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PASSLY_ISSUER_URI:http://localhost:8080/realms/passly}
          jwk-set-uri: ${PASSLY_JWKS_URI:}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
