spring:
  application:
    name: catalog-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PASSLY_ISSUER_URI:http://localhost:8080/realms/passly}
          jwk-set-uri: ${PASSLY_JWKS_URI:}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
